name: Enable automerge on dependabot PRs

on:
  # See note below about using pull_request_target
  pull_request_target:

jobs:
  automerge:
    name: Enable automerge on dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Enable automerge on dependabot PRs
        uses: daneden/enable-automerge-action@v1
        with:
          # A personal access token that you have generated and saved in the
          # repo or org’s encrypted secrets
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          # The name of the PR author to enable automerge for
          # Defaults to dependabot[bot]
          allowed-author: "dependabot[bot]"

          # Allowed values: MERGE | SQUASH | REBASE
          # Defaults to MERGE
          merge-method: MERGE
# This workflow deploys The Language Hub on a successful PR
# name: auto-merge

# on:
#   pull_request:
#     branches: [learn-data]

# jobs:
#   auto-merge:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: ahmadnassri/action-dependabot-auto-merge@v2
#         with:
#           target: minor
#           github-token: ${{ secrets.ADMIN_GITHUB_TOKEN  }}

# name: CI

# # Controls when the action will run. Triggers the workflow on push or pull request events
# on:
#   pull_request:
#     branches: [learn-data]

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   merge:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       - uses: actions/checkout@v2
#         with: ${{ secrets.ADMIN_GITHUB_TOKEN }}
#       - uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
#         with:
#           target: patch
#           token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
